### ISSUE TITLE
CustomEvent is not constructible in IE11

### ISSUE THREAD

**Issue by bicknellr** [webcomponents/html-imports#25]
There are a couple of places where the polyfill tries to construct a CustomEvent but IE11 doesn't support this, causing it to throw:
https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L568
https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L764

**Comment by valdrinkoshi** [comment]
The expectation is for the user to include webcomponents/webcomponents-platform polyfills for that (see tests/polyfills.js)
Should probably update the readme about this ;)

**Comment by bicknellr** [comment]
👍
