### ISSUE TITLE
[v1] `.import` is not an instance of Document

### ISSUE THREAD

**Issue by tomalec** [webcomponents/html-imports#3]
In polyfilled browsers, `link.import instanceof Document` is false

```html
    <script>
        function importLoaded(event) {
          chai.assert.ok(event.target.import instanceof Document, 'load event target can be used to find imported document');
        }
    </script>
    <link rel="import" href="imports/load-smth.html" onload="importLoaded(event)">
```

As per spec https://www.w3.org/TR/html-imports/#interface-import

> the attribute **must** return the _imported document_ for the _import_

and for "_imported document_"

> an _import_ is represented as a _`Document`_, called the **imported document**.

**Comment by tomalec** [comment]
@valdrinkoshi wrote at https://github.com/webcomponents/html-imports/pull/4#discussion_r95232320
> In the new polyfill we're experimenting the benefits of not having a separate Document created for each import, but rather just an Element.

So, are you compromising compliance with (formerly) to be spec for better performance? So we will no longer be able to use separated/isolated  `document.head`, `document.body`, `document`-wide events and everything will pollute main one, we will not be able to traverse up using `.parentElement` without a risk to leak outside of the imported document?

**Comment by valdrinkoshi** [comment]
Yes, the gambit is to use an `Element` instead of a disconnected `Document`, which makes the implementation simpler (e.g. we can use the native `currentScript, ownerDocument`, we don't require to polyfill `<base>`, we don't need to clone styles in order to apply them).
Also, this implementation is closer to the [vulcanize](https://github.com/Polymer/vulcanize) implementation, as it inlines the contents of imports.

Concerning the events, yes they'll potentially pollute the main document. Did you experience issues with this approach?

**Comment by tomalec** [comment]
> we don't require to polyfill `<base>`

So, we will not be able to use paths relative to importing sub-document, but to use always paths relative to the main doc? That would be huge obstacle.

> we don't need to clone styles in order to apply them

Yeah, I do feel the problem, as I was experiencing polyfill limitation-related issues for years, I think there is still one issue on Chromium that occurred to be side effect of it ;) As well as the problem with imported `<scripts>` which either get wrong `currentScript`, wrong `.previousElementSibling` or are fired too late. So, I really understand the need and the benefits.

> Concerning the events, yes they'll potentially pollute the main document. Did you experience issues with this approach?

I haven't experienced issues with this yet, as we are struggling with more issues with v1 and Polymer 2 migration, in more initial parts of our system, even in Chrome with native HTML Imports support.

However, we and our customers (as we are developing in-memory application platform), are using HTML Imports isolation heavily. For example, to build the structure in imported document (out of sub-imported docs) before stamping it to the main doc.

I'm afraid mostly of polluting and conflicting events plus the lack of `.ownerDocument` & `.parentElement` limit.

Unfortunately, I will not be able to give any specific, real-life use-cases, until we will manage to workaround Polymer's databinding issues, and migrate bigger chunk of our system, to be able to fidle with this polyfill. (Hopefully somewhere in mid-Feb)

**Comment by valdrinkoshi** [comment]
> So, we will not be able to use paths relative to importing sub-document, but to use always paths relative to the main doc?

Do you mean a use-case like this? e.g. 
- index.html imports `elements/my-element`
- my-element.html imports `elements/third-party/other-element`
- both rely on `<base>`
```html
<!-- index.html -->
<base href="elements/">
<link rel="import" href="my-element.html">

<!-- elements/my-element.html -->
<base href="third-party/">
<link rel="import" href="other-element.html">
```
That's a limitation of the new approach, needs to be supported.

**Comment by tomalec** [comment]
Yes that's the use case, but multiply depth by 10, amount of imports on each level by 10, consider documents with not just custom elements definitions but bigger parts of HTML, add resolutions of paths to styles, images and scripts.


> That's a limitation of the new approach, needs to be supported.

Great to hear that :)

**Comment by valdrinkoshi** [comment]
Concerning `.ownerDocument` and `.parentElement`, the thinking is to provide an API to get the limitation, e.g. `HTMLImports.getImportForNode()`
I'm working on clarifying all these in README.md in #1, stay tuned :)

**Comment by tomalec** [comment]
Thanks for https://github.com/webcomponents/html-imports#linkimport-is-not-a-document @valdrinkoshi  :)
I found another consequence of such approach. `<body>` and `<head>` tags are stripped from imported document. That may break CSS selectors and JS traversing.

**imported.html**
```html
<head>
    <template>...</template>
</head>
<body class="custom-body">
    <h1>Hello World!</h1>
    <script>
        const ownerDoc = HTMLImports.importForElement(document.currentScript);
        let someElement = ownerDoc.querySelector('.custom-body > h1'); // null
        ownerDoc.head.querySelector('template'); // error: ownerDoc.head is undefined
    </script>
</body>
```

Do you think it's worth adding a notice on that to the README as well?
