### ISSUE TITLE
some advertisement for bundledom :)

### ISSUE THREAD

**Issue by kapouer** [webcomponents/html-imports#5]
Hi,

i've started using HTMLImports in new projects some months ago.
We quickly realized the accumulation of dozens of imports was asking for a solution for bundling everything back into a single js file, so i developed https://github.com/kapouer/bundledom, a simple tool for bundling all css/js/imports into a single js file (or in one js and one css file).
This means that during development we go HTMLImports everywhere, and in production it's no longer needed, instead we emulate the `document._currentScript` thing.
I think this kind of usage of HTMLImports gives a nice twist to the concept.

**Comment by eugef** [comment]
There is already a [Vulcanize ](https://www.polymer-project.org/1.0/docs/tools/optimize-for-production) tool that does exactly the same.

**Comment by kapouer** [comment]
Probably none, but i wasn't aware of that one !

**Comment by kapouer** [comment]
Actually the difference is that it bundles imports, scripts, stylesheets in two files (css / js), instead of inlining. It also adds default postcss filters and js minifier, and can be configured using a "common" html file. It's a bit of "don't do it yourself" cli that tries to work out of the box, as opposed to gulp config - which is far stronger but i couldn't figure how to make gulp do the job vulcanize do at the moment of writing bundledom. I'll probably rewrite it do use gulp instead then.
