### ISSUE TITLE
Including HI breaks code

### ISSUE THREAD

**Issue by oravecz** [webcomponents/html-imports#51]
I am not using HTML Imports in my code, but the Polyfill is impacting my web component class inheritance is a very strange manner. I noticed this when I included `webcomponents-lite.js` in my project. Before I was using `webcomponents-sd-ce.js` and I didn't have the problem.

I am using the Constructor-Mixin coding practice in ES6 to simulate a class structure while supporting mixins. This code will be simplified.

```
class MyElement extends HTMLElement {

    set items (value) {
        this._items = value   <-- Never executes
    }
}

// index.html
myElement.items = [ ... ]
```

My original code was working as expected when including `webcomponents-sd-ce` my code worked as expected. When switching to `webcomponents-hi-sd-ce` the setter function never gets invoked. 

It will take me some time to try to isolate this issue as it doesn't happen for all of my components, but I am posting it now to see if it is a known problem.

**Comment by valdrinkoshi** [comment]
Hi @oravecz, are you using imports in your project? The polyfill guarantees the correct order of execution of the imported scripts, so this might be related to missing dependencies in the import? 

In the main document, you should wait for the `WebComponentsReady` event before you can safely assume that all the polyfills have loaded and are ready to be used, as for when using [`webcomponents-loader.js`](https://github.com/webcomponents/webcomponentsjs#webcomponents-loaderjs)
```js
window.addEventListener('WebComponentsReady' , function() {
    // At this point we are guaranteed that all required polyfills have loaded,
    // all HTML imports have loaded, and all defined custom elements have upgraded
    let MyElement = customElements.get('my-element');
    let element = document.querySelector('my-element');
    console.assert(element instanceof MyElement);  // 👍
    element.someAPI(); // 👍
});

**Comment by oravecz** [comment]
I tried to use the `webcomponents-loader`, and it correctly identified the `webcomponents-sd-ce.js` file and loaded it. However, the `WebComponentsReady` custom event did not fire. I did a search in the `webcomponents-sd-ce.js` file, but did not find this event being triggered.

It looks like the event is raised in the loader only when there are no polyfills loaded.

**Comment by valdrinkoshi** [comment]
Can you provide more details? E.g. what browser & webcomponentsjs flags are you using?

**Comment by oravecz** [comment]
I probably should of raised the problem with `webcomponents-loader` as a separate issue. Let me do that.
https://github.com/webcomponents/webcomponentsjs/issues/734
