### ISSUE TITLE
Calling HTMLImports.whenReady in an import load handler causes other load events to be lost

### ISSUE THREAD

**Issue by Artur-** [webcomponents/html-imports#57]
If you import multiple HTML files, then all files are imported before any load events are fired.  If one listener for an HTML import happens to call `window.HTLMImport.whenReady` inside the load handler, then further load listeners might not be called. 

The call to `whenReady` ends up in `whenImportsReady`, which in turn calls `whenElementLoaded` for all imports - also for those who have not yet had a chance of firing their `load` event. For some reason `whenElementLoaded` assumes that 
```
// This import has already been loaded but its __loaded property got removed. Ensure we set it back!
```
and will set the `__loaded` property for imports - preventing the event firing logic to work correctly once control is returned there.

This can be seen in https://jsbin.com/xesewocohu/1/edit

In Chrome you get an output of

```
"Loading paper-input"
"Loading paper-slider"
"paper-input loaded"
"paper-slider loaded"
"All imports loaded and ready to use"
"All imports loaded and ready to use"
```

In Firefox you get
```
"Loading paper-input"
"Loading paper-slider"
"paper-slider loaded"
"All imports loaded and ready to use"
```

**Comment by valdrinkoshi** [comment]
This is caused by the change done in https://github.com/webcomponents/html-imports/pull/46, which was a tentative to workaround this GC issue on Chrome 57 https://bugs.chromium.org/p/chromium/issues/detail?id=701601
