### ISSUE TITLE
Browsers Inequality , is it a bug ?

### ISSUE THREAD

**Issue by dimwell-git** [webcomponents/html-imports#60]
This issues is based on the following believes: 

1. Polyfill adds missing functionality to the browser
2. One input provides same output on different browsers.

I decided to make a test based on the spec: [link](http://w3c.github.io/webcomponents/spec/imports/index.html)

**Input:**

- 8 fiels: A,B,C,D,E,F,G,H

**A**

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="html-imports.min.js"></script>
    <script>
        console.log("print from: A <head>");
    </script>
    <link rel="import" href="imports/B.html">
    <link rel="import" href="imports/C.html">
    
</head>
<body> 
    <script>
        console.log("print from: A <body>");
    </script>
</body>
</html>
```

**B**
```
<script>
    console.log('print from: B');
</script>
<link rel="import" **href="D.html">
```

**C**
```
<script>
    console.log('print from: C');
</script>
<link rel="import" href="D.html">
<link rel="import" href="E.html">
<link rel="import" href="G.html">
```

**D**
```
<script>
    console.log('print from: D');
</script>
<link rel="import" href="F.html">
<link rel="import" href="B.html">
```

**E**
```
<script>
    console.log('print from: E');
</script>
<link rel="import" href="H.html">
```

**F**
```
<script>
    console.log('print from: F');
</script>
```

**G**
```
<script>
    console.log('print from: G');
</script>
```

**H**
```
<script>
    console.log('print from: H');
</script>
```

**Chrome Output [Version 58.0.3029.110 (64-bit)]**
```
print from: A <head>
print from: B
print from: D
print from: F
print from: C
print from: E
print from: H
print from: G
print from: A <body>
```

**Firefox [53.0.2 (64-бит)] and Safari [Version 9.1.2 (11601.7.7)]**
```
print from: A <head> 
print from: A <body>  
print from: B  
print from: D  
print from: F  
print from: C 
print from: E 
print from: H 
print from: G
```

**Comment by valdrinkoshi** [comment]
The main reason is that the polyfill cannot block the parser & at the same time being performant & csp compliant.

**Comment by valdrinkoshi** [comment]
Rationale from the README:
> The polyfill fires the HTMLImportsLoaded event when imports are loaded, and exposes the HTMLImports.whenReady method. This api is necessary because unlike the native implementation, script elements do not force imports to resolve. Instead, users should wrap code in either an HTMLImportsLoaded handler or after load time in an HTMLImports.whenReady(callback) call.
