### ISSUE TITLE
Relative import in absolutely imported file resolves relative to wrong directory in Safari

### ISSUE THREAD

**Issue by Legioth** [webcomponents/html-imports#62]
The chain of imports needed to reproduce this is as follows:
* `/a/index.html` loads the polylfill and imports `a.html`
* `/a/a.html` imports `/b/b.html`
* `/b/b.html` imports `c.html`

Opening `/a/index.html` in Safari 10.1.1 with the the current master version of `html-imports.min.js` (b07d2b9125dd41a5b0b2280eaba9f55500934d2d) results in loading both `/a/c.html` and `/b/c.html`. Maybe also related to this issue is that the network inspector in Safari shows that  `/a/c.html` and `/b/b.html` are both downloaded twice.

Using the polyfill in Firefox or the native implementation in Chrome only loads the expected `/b/c.html` and never `/a/c.html`.

The issue can be worked around with either of these changes:
* `/a/index.html` directly imports `/b/b.html` instead of importing `a.html`, or
* `/a/a.html` is changed to import `../b/b.html` instead of `/b/b.html`

Edit: Attached example file structure: [safariRelativeImport.zip](https://github.com/webcomponents/html-imports/files/1080717/safariRelativeImport.zip). `a/index.html` should only show a green square, but shows a green square with a red border in Safari.

**Comment by valdrinkoshi** [comment]
The problem seems to be on Safari where urls like `/b/b.html' are not resolved. I think the best place to fix this is in `XHR.load`, where we could use [responseURL](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseURL) to compute the redirectedUrl
