### ISSUE TITLE
Process imports added to <body>

### ISSUE THREAD

**Issue by tomalec** [webcomponents/html-imports#68]
Given
> The polyfill supports dynamically added imports by observing mutations in `<head>` and within other imports; it won't capture imports appended in `<body>`.
 https://github.com/webcomponents/html-imports#dynamic-imports

Is there an API to manually process HTML Imports dynamically added to the `<body>`? Like [`loadImports`](https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L226)

**Comment by valdrinkoshi** [comment]
The polyfill doesn't observe mutations on body for performance reasons. The advice would be to append the import in `<head>`.

If the import is inside another already processed import which is in body, that will be captured and processed too, e.g.
```html
<body>
  <link id="myImport"  href="my-import.html" rel="import">
  <button onclick="loadOtherImport()">load other import</button>
  <script>
    function loadOtherImport() {
      var other = document.createElement('link');
      other.rel = 'import';
      other.href = 'other-import.html';
      myImport.import.appendChild(other);
    }
  </script>
</body>
```

**Comment by tomalec** [comment]
But what if the import is inside main document's body appended by the third party?
It would be great if I could do
```js
somenode.addEventListener('doc-frag-stamped', function(){
    HTMLImports.loadImports(/*{DocumentFragment | Node}*/ somenode);
});

**Comment by valdrinkoshi** [comment]
I assume you already have a way to detect that the import was appended in body, right? You could re-parent it into document's head so it can be processed.
Could you share the scenario you're into? Curious to see who imports who and where :)
I'm trying to figure a solution that doesn't require html-imports to change behavior, as it would be less performante to observe mutations in the whole document. Also, APIs like loadImports are non-standard so I'm a bit hesitant on exposing

**Comment by valdrinkoshi** [comment]
@tomalec gentle ping, following your example, you could reparent `somenode` to be into `<head>`, e.g.
```js
somenode.addEventListener('doc-frag-stamped', function(){
    document.head.appendChild(someimportlink);
});
```
Would something like this work?

**Comment by tomalec** [comment]
Thanks for the comments, and sorry for the late response.

> You could re-parent it into document's head so it can be processed.

In short, for my case, the answer is "no".

Even though I do stamp and can control when I do so, I'm not the owner of the stamped document fragment. (see https://github.com/Juicy/imported-template, https://github.com/Juicy/juicy-html, https://starcounter.io/html-partialsincludes-webcomponents-way/)
Therefore, I would like to avoid moving elements around, as author's code may rely on its position. Also, I'd have to handle moving it back again manually from `head` if its parent element gets removed.

**Comment by valdrinkoshi** [comment]
Strictly speaking of imports, author's code wouldn't be able to rely on its position in the dom: as an example, `polymer.html` is imported by many other imports, but `polymer.html` cannot rely on the position where it is imported, as there will be many links importing that url, but only the first one in the document will actually trigger the loading of the file, while the other import links will just have a pointer to the import document fragment (via `link.import`).

You could clone the import link and append the clone in `<head>`, so that authors will still have the link at the correct position, while the clone would trigger the loading.
```js
somenode.addEventListener('doc-frag-stamped', function() {
   if (document.head.contains(someimportlink) === false) {
      document.head.appendChild(someimportlink.cloneNode());
   }
});
```
Would this be acceptable?

**Comment by tomalec** [comment]
> Strictly speaking of imports, author's code wouldn't be able to rely on its position in the dom


imports author code cannot, but in my case author's code is the document fragment that contain an import, and this one is able to rely on its position.

Look at it that way:
1. I am the implementer of `<clientside-include>`,
2. The Author is the user of my element and author of `partial.html`. So he/she does:
   **index.html**
   ```html
   <body>
     <h1>Hello</h1>
     <clientside-include href="partial.html"></clientside-include>
   </body>
   ```
   **partial.html**
   ```html
   <link rel="import" href="my-app.html">
   <script>
     document.currentScript.previousElementSibling.onload = ()=>{
       console.info('my app dependencies are ready!');
     };
   </script>
   <my-app></my-app>
   ```
   
---

Looks really tricky, as I would have to actually hardcode polyfill internal quirks into my own codebase.
Also `someimportlink.onload`, `someimportlink.import`, etc. would not work at all.

Unless I'll reimplement/mirror them. But this looks like an overhead to me, since all the bits are already here.

**Comment by valdrinkoshi** [comment]
Oh I understand, thanks for taking the time to clarify! I guess the least worse is to expose `loadImports` rather than observe all changes in `<body>`...

**Comment by tomalec** [comment]
I'm fine with a single call to polyfill method. It becomes explicit that it's a solution to polyfill caveat but as simple and clean as it could be not to tie polyfill internals in my codebase. I think it's a fair trade between common cases performance vs. maintainable support for all other valid cases.
