### ISSUE TITLE
missing square brackets around import-dependency

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/html-imports#69]
https://github.com/webcomponents/html-imports/blob/2fdce2cb070c1c08664aed704b187d0854092c06/src/html-imports.js#L190

I think the intent is to produce this selector: `link[rel=import]:not([import-dependency])`, but it produces `link[rel=import]:not(import-dependency)` which does **not** ignore those imports marked with `import-dependency`.

**Comment by valdrinkoshi** [comment]
Oh that's true, good catch!
