### ISSUE TITLE
Execute imports earlier in IE

### ISSUE THREAD

**Issue by eugef** [webcomponents/html-imports#7]
The current version of HTMLImport polyfill that is shipped in WebComponents polyfill v0.7.x has an issue in IE - html imports are executed with a huge delay. 

Here is detailed discussion: https://github.com/webcomponents/webcomponentsjs/issues/597

In short - the reason is that only for IE polyfill waits when `document.readyState` is `complete`, but not when it is `interactive`.

Are there any plans to fix it? Do you need any help with that?

**Comment by valdrinkoshi** [comment]
Hi @eugef, thanks for reporting this! Fixing this should be quite trivial, but testing it might not. I'm currently working on a major refactoring in #1, and tried to apply the fix and tests are still passing on IE11/Edge. It would be really helpful to have a couple of unit tests targeted to this issue, if you have some time would you like to help on that?

**Comment by eugef** [comment]
@valdrinkoshi yes i would like to help with testing.
I can do some manual testing on a rela website where i experience this issue.
Not sure i f it is possible to create unit test for that, as it is mostly about performance.

**Comment by valdrinkoshi** [comment]
@eugef sure, mind trying the `cleanup` branch? https://github.com/webcomponents/html-imports/tree/cleanup
