### ISSUE TITLE
Duplicate request with absolute paths

### ISSUE THREAD

**Issue by ChrisEbert** [webcomponents/html-imports#72]
When using absolute paths without a hostname to import a html file, the file is imported twice. 

Given: `<link rel="import" href="/components/my-component.html">`

The import polyfill starts two requests (the apps base is `/`):
1. `/components/my-component.html`
2. `http:///localhost/components/my-component.html`

As I can see here (https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L81), relative paths are resolved to absolute paths with the current host. But paths detected as absolute paths (with or without host) are skipped.

Is this a desired behavior? I guess changing that would result in breaking changes of the polyfill.

**Comment by valdrinkoshi** [comment]
@ChrisEbert I tested this locally, and I cannot repro the issue:
- clone html-imports repo
- create `test.html`
```html
<script src="html-imports.min.js"></script>
<link rel="import" href="/components/html-imports/test-element.html">
<link rel="import" href="http://localhost:8081/components/html-imports/test-element.html">
```
- create `test-element.html`
```html
<script> console.log('hello from test-element.html');</script>
```
- serve resources with `polymer serve`
- navigate to http://localhost:8081/components/html-imports/test.html from safari or firefox
- check dev console

I see only 1 log, and in the network tab i see test-element.html loaded only once

**Comment by ChrisEbert** [comment]
It assumes the issue appears only in safari and when requesting files from components and not the main index.html.

Take a look at my structure: https://github.com/ChrisEbert/html-imports-testcase

![request](https://raw.githubusercontent.com/ChrisEbert/html-imports-testcase/master/request.jpg)
This results in duplicate component definition errors - `SyntaxError: Can't create duplicate variable: 'XSubcomponent'`

The request path inside the polyfill for the first file is`/src/subcomponent.html` and for the second (last) one `http://localhost:8081/src/subcomponent.html`. 

I know, it's no common the way to reference a file like that but it suits the needs in my project. 😄  Chrome does everything right, so I assume the polyfill should too.

Thank you for your effort!

**Comment by valdrinkoshi** [comment]
Oh wow, that's very weird! Thanks for the repro, will investigate.

**Comment by valdrinkoshi** [comment]
Turns out that `link.href` gets resolved only when the element is connected in Safari 😮

**Comment by ChrisEbert** [comment]
Awesome, thank you guys!
