### ISSUE TITLE
Use an anchor instead of new URL

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/html-imports#8]
Then we can nuke the `URL` polyfill and live happily ever after.

/cc @sorvell who can help with implementing hints

**Comment by kevinpschaaf** [comment]
Refer to basic technique employed in Polymer of using a disconnected document with a `<base>` tag and `<a>` tag, and modulating the baseURI and reading the `href` from the anchor: https://github.com/Polymer/polymer/blob/2.0-preview/src/template/resolve-url.html#L55-L63

**Comment by kapouer** [comment]
Isn't it awfully expensive to create a document for that ?

**Comment by valdrinkoshi** [comment]
Being fixed in #1, we lazily feature-detect if we can use `URL`, and if not, we use the disconnected document trick.
