### ISSUE TITLE
html import link can only read once bug!

### ISSUE THREAD

**Issue by xgqfrms** [webcomponents/html-imports#86]
# `html import link` can only read **once** bug!

> more details, as below screen shortcuts shows:

![image](https://user-images.githubusercontent.com/7291672/41828172-603c3f56-7866-11e8-8e27-543309d98932.png)

## after I read ` link.import` once, It template content will be cleared.

> before 

![image](https://user-images.githubusercontent.com/7291672/41828228-c2148508-7866-11e8-9f77-5fea262e451f.png)

![image](https://user-images.githubusercontent.com/7291672/41828298-0bd8246a-7867-11e8-8280-dd20b523635a.png)

![image](https://user-images.githubusercontent.com/7291672/41828331-401341ec-7867-11e8-99b7-42c81dc8c1c2.png)

> after

![image](https://user-images.githubusercontent.com/7291672/41828578-9d0771c4-7868-11e8-871a-837d9b280f03.png)

![image](https://user-images.githubusercontent.com/7291672/41828624-ee43251a-7868-11e8-9d2d-9e78784c4009.png)

**Comment by xgqfrms** [comment]
# demo

https://cdn.xgqfrms.xyz/HTML-imports/templates/index.html

**Comment by xgqfrms** [comment]
# node clone

![image](https://user-images.githubusercontent.com/7291672/41832762-01f919ea-7880-11e8-9637-15e64cf1c353.png)

**Comment by valdrinkoshi** [comment]
Looks like you're not using the `HTMLImports` polyfill in that example.
I skimmed through your index.js code and noticed you're waiting with `setTimeout( ... , 0)` before parsing the imports.

I think over there you should be waiting for the imports to be fully loaded. You can do that by either using this polyfill and listening for `HTMLImportsLoaded` event, or by using `whenReady()` method.
```js
document.addEventListener('HTMLImportsLoaded', function() { 
  // ...
});
// Works the same
HTMLImports.whenReady(function() {
  // ...
});
```
If you want to support only native HTML Imports and not use this polyfill, you just need to wait for document.readyState to be done loading, e.g. see how we do it:
https://github.com/webcomponents/html-imports/blob/dd65180543b34787a77fbd3511702262284117bb/src/html-imports.js#L620-L631

**Comment by xgqfrms** [comment]
@valdrinkoshi Thanks for your time!

**Comment by xgqfrms** [comment]
# the solution

> dynamic html imports

https://github.com/webcomponents/html-imports#dynamic-imports

![image](https://user-images.githubusercontent.com/7291672/47344767-c79df580-d6db-11e8-8100-061dfd8b00b2.png)
