### ISSUE TITLE
HTML Imports deprecated, potentially breaking site?

### ISSUE THREAD

**Issue by Kritzzz** [webcomponents/html-imports#89]
Seeing as HTML Imports is deprecated in M70 and will be removed at M73 (around March 2019) according to [Chrome Platform Status](https://www.chromestatus.com/features/5144752345317376).

Will a site using HTML Imports with webcomponents be broken after March 2019, or does webcomponentsjs act as a polyfill/workaround to the deprecation?

**Comment by web-padawan** [comment]
> does webcomponentsjs act as a polyfill/workaround to the deprecation?
This is the correct statement. See also [Web Components v0 deprecations
](https://www.polymer-project.org/blog/2018-10-02-webcomponents-v0-deprecations) post in Polymer blog.
