### ISSUE TITLE
Import not re-fetched on error

### ISSUE THREAD

**Issue by LarsDenBakker** [webcomponents/html-imports#91]
When a HTML import fails once, it will never be re-fetched when imported again. This is because it will hit this line on re-import: https://github.com/webcomponents/html-imports/blob/master/src/html-imports.js#L262 and it will use the stored error state without re-attempting the XHR.

We code split all our pages, and when a user fails to dynamically import (for example due to flaky network) a page they might try again. They will keep hitting the error in this case.

I don't know how much energy will be put into HTML imports, we're going to move to modules and use webpack for our older polymer 2 components. But in case anyone else runs into this, now they know why.

**Comment by azakus** [comment]
HTML Imports are deprecated, and we are only making critical bug fixes
